### PR TITLE
Consolidated columns in About page, added timeouts to Login page

### PR DESCRIPTION
**Pull request by itsmistad**
- Reformated and adjusted some of the text in the About page
- Fixed login.css caching regardless of changes
- Added a sign-in redirection timeout to the Login page (in case the user logged in with the wrong account and wants to log out)
- Added a "redirecting..." message
- Signing out will now keep you on the Login page and toggle the appropriate elements

### CODE REVIEW

**Review by TylerCarey98 — CHANGES_REQUESTED** [review]
Somethings wrong/broken, google authentication wont let me sign in when prompted.
Broken

**Comment by itsmistad** [comment]
@TylerCarey98 Try now

**Comment by TylerCarey98** [comment]
Multiple functionality bugs are still present, lets meet in person to discuss so its easier to see. 😸

**Review by TylerCarey98 — APPROVED** [review]
Fixed and approved, good changes.

**Pull request merged**
